export const project_info = [
  {
    size: 200,
    title: "Otter USV R&D",
    ref: "otter-usv",
    blurb: [
      "I've been deeply involved in several significant projects centered around the Maritime Robotics Otter Uncrewed Surface Vessel (USV) at Ingenuity Labs, each contributing to its capabilities and functionality.",
      "In the first phase, I embarked on a series of boat upgrades and hardware integrations. This included attaching LiDAR to the Otter via a meticulously crafted 3D printed mount. I designed and fabricated four distinct 3D printed components to enhance the Otter's performance and adapt it for specific tasks. Additionally, I played a pivotal role in the wiring and concept development of a payload hardware box. This comprehensive unit incorporated an ethernet switch, power board, Jetson Orin, and radio components, optimizing the Otter's hardware for advanced functionalities.",
      "Another significant milestone in this journey involved programming a Robot Operating System 2 (ROS2) driver package tailored to interface seamlessly with the Otter USV's proprietary hardware. This effort included the creation of five custom data types, streamlining control, and enabling data reception, including GPS, IMU, power metrics, and odometry data generated by a Kalman filter. This ROS2 integration elevated the Otter's capabilities and paved the way for advanced control and data analysis.",
      "The most groundbreaking achievement was the development and publication of a pioneering particle-filter-based global localization algorithm, specifically designed for the Maritime Robotics Otter USV. This algorithm proved invaluable for accurate localization in GPS-denied environments, achieving up to 20 meters of global accuracy. Leveraging satellite imagery and LiDAR data, the algorithm employs a unique approach. It simulates LiDAR scans of the shoreline by raycasting on regional satellite imagery from random locations, comparing these simulated scans with real LiDAR point clouds to generate precise estimates of the Otter's position. This innovative algorithm adapts the scan matching step of a traditional particle filter to USV localization challenges, significantly enhancing the Otter's navigational capabilities.",
      "These endeavors culminated in comprehensive in-water testing, conducted across four distinct locations in Kingston and Minden, Ontario. These tests underscored the practical impact of our work, validating the Otter's enhanced capabilities in various real-world scenarios. These projects collectively demonstrate my commitment to advancing autonomous marine technology and my capacity to deliver tangible results in complex, real-world environments.",
    ],
    embed: [],
    imgs: [
      { src: "https://i.imgur.com/O9p8jia.jpg", size: "500px" },
      { src: "https://i.imgur.com/ivFebMj.jpg", size: "500px" },
    ],
    soft_skills: [
      "Collaboration, Live Project Demonstration, Iterative design, Collecting Requirements, Research and Development",
    ],
    tech: [
      "ROS2, C++, Python, LiDAR, 3D Printing, OpenCV, Git, Linux,  Particle Filters",
    ],
    more: true,
  },
  {
    size: 200,
    title: "CO2 Monitoring Lynx Rover",
    ref: "lynx-rover",
    blurb: [
      "A four-wheeled autonomous rover was modded with the primary objective of generating a heat-map illustrating CO2 concentration levels across a LiDAR SLAM-generated floorplan. This rover was successfully demonstrated to an audience of over 50 students and professors.",
      "The rover's sensor suite comprises a LiDAR unit, encoders, sharp infrared sensors, an SGP30 CO2 Sensor, an RPLiDAR, and a gyroscope and accelerometer IMU. Systems integrated to pursue the objective include joypad control, a PID Controller for precise motion, pre-packaged SLAM for environment mapping, and the implementation of a specialized algorithm to create CO2 concentration heat maps using sensor data, occupancy grids, and matplotlib visualization.",
    ],
    embed: [],
    imgs: [
      { src: "https://i.imgur.com/3ZmIaMh.png", size: "300px" },
      { src: "https://i.imgur.com/vcIysZ9.png", size: "300px" },
    ],
    soft_skills: ["Collaboration, Live Project Demonstration"],
    tech: ["Python, ROS, SLAM, LiDAR, IMU, Matplotlib"],
    more: true,
    project_url: {
      creator: "sabrinabutton",
      repo: "ros_slam_heat_map",
      url: "https://github.com/sabrinabutton/ros_slam_heat_map",
    },
  },
  {
    size: 100,
    title: "Model Autonomous Mining Loader",
    ref: "model-auto-loader",
    blurb: [
      "Created a line-follower navigation algorithm for a robot equipped with an Arduino Uno, SHARP infrared sensors, and DC motors. Designed and modelled a scoop and arm mechanism using Linkage, and expanded the program to perform tasks such as scooping, carrying, and dropping dirt on queues from the infrared sensors.",
    ],
    embed: [],
    imgs: [
      { src: "https://i.imgur.com/vdXwthr.png", size: "300px" },
      { src: "https://i.imgur.com/avLETse.png", size: "300px" },
      { src: "https://i.imgur.com/ioj2Dz9.png", size: "400px" },
    ],
    soft_skills: ["Live Project Demonstration, Iterative design"],
    tech: ["Arduino, C, Mechanical-prototyping"],
    more: false,
    project_url: {
      creator: "sabrinabutton",
      repo: "autonomous_mining_loader",
      url: "https://github.com/sabrinabutton/autonomous_mining_loader",
    },
  },
  {
    size: 100,
    title: "Antenna-Angler Robotic Arm",
    ref: "antenna-arm",
    blurb: [
      "This project was undertaken to enhance the signal strength of an outdoor antenna. It involves an antenna affixed to a servo-motor-driven robotic arm, which assesses signal strength at specific angles and adjusts its orientation to optimize internet connectivity. The Arduino platform was utilized to program the servos and communication functions, interfacing with a computer through serial port communication, and featuring a C-based GUI.",
    ],
    embed: [],
    imgs: [{ src: "https://i.imgur.com/UNprItT.png" }],
    soft_skills: ["Iterative design"],
    tech: ["Arduino, C, Mechanical-prototyping"],
    more: false,
  },
  {
    size: 500,
    title: "Payload Testing Apparatus, Queen's Space Engineering Team",
    ref: "payload-testing",
    blurb: [
      "The “Payload Testing Apparatus” aimed to fulfill Queen’s Space Engineering Team’s need for a chemical testing device to conduct wet chemical tests during the fall semester, in advance of the rover's payload assembly in the winter semester. The apparatus is for laboratory use, aimed at detecting biosignatures in soil samples. Three distinct models were devised to meet the client's specifications, all featuring a cylindrical body, sieve, funnel, and soil sample pathway leading to cuvettes for wet chemical biosignature testing. The chosen design prioritized simplicity and effectiveness, employing a manually operated sieve and a clever distribution system. This fully non-electric apparatus, designed with a focus on user-friendliness, efficiently grinds soil samples, distributes them evenly, and facilitates varied cuvette placement for testing. The selection of this design was based on its minimized points of failure, cost-effectiveness, and lightweight construction, although it may be less adept at grinding coarse grains compared to designs with electric motor-driven sieves. I played key roles in brainstorming, making design choices, developing this model in CAD software, creating system diagrams, and providing technical documentation; This project was extremely beneficial to my teamwork skills, improved my abilities to collect and implement requirements by a client, and ignited my passion for integrated mechanical design.",
    ],

    embed: [],
    imgs: [
      { src: "https://i.imgur.com/WkFxC4L.png" },
      { src: "https://i.imgur.com/cextWLq.jpg" },
    ],
    soft_skills: ["Teamwork"],
    tech: ["SolidWorks Protoyping, Mathematical Modeling"],
    more: true,
  },
  {
    size: 100,
    title: "Pneumonia/Covid Chest X-Ray Recognition ML Model",
    ref: "covid-ml",
    blurb: [
      "Machine learning practice project which applies a simple neural net to determine if a lung x-ray depicts a patient with Covid-19, or pneumonia. ",
    ],
    embed: [],
    imgs: [],
    soft_skills: [],
    tech: ["Python, Tensorflow, Keras, Machine Learning"],
    more: false,
    project_url: {
      creator: "sabrinabutton",
      repo: "covid-pneumonia-ml",
      url: "https://github.com/sabrinabutton/covid-pneumonia-ml",
    },
  },
  {
    size: 400,
    title: "Arduino LEGO Game Console",
    ref: "game-console",
    blurb: [
      "Amid the COVID-19 pandemic, I embarked on a weekend project that showcased my ingenuity and resourcefulness. Inspired by the online gaming console creations utilizing Raspberry Pi, I sought to replicate a similar concept using an Arduino, spare push buttons, and a display salvaged from a previous endeavor.",
      "To realize this idea, I ingeniously prototyped the console's housing using LEGO bricks. This allowed for precise customization, featuring strategically placed holes for convenient access to the Arduino ports, a dedicated panel for the buttons, and a secure enclosure for the LCD display. The modular design even enabled easy removal of the LCD panel to access the Arduino and the terminal block, which managed connections between the buttons and Arduino I/O pins.",
      "Taking a creative approach, I leveraged binary matrices to craft custom LCD-printable characters for an interactive game. In this game, the user-controlled character navigated the screen, collecting gifts while avoiding traps through button inputs. The gameplay mechanics involved manipulating the LCD display matrix and adjusting character coordinates based on user inputs or predefined paths. The gifts and traps were dynamically generated, constantly advancing towards the left side of the screen, adding an element of challenge and excitement to the gaming experience.",
      "For a visual demonstration of this project, please refer to the embedded video above.",
    ],
    embed: [{ src: "https://www.youtube.com/embed/8fNFOhTsp44" }],
    imgs: [],
    soft_skills: ["Creativity :)"],
    tech: [
      "Arduino, Physical Prototyping, I/O Systems, Custom LCD Character Creation",
    ],
    more: true,
  },
  {
    size: 500,
    title: "ReCoin, UofT Hacks IX 3rd Overall Winner",
    ref: "recoin",
    blurb: [
      "In just 36 hours, our team of four created the ReCoin app for UofT Hack IX, addressing the theme of 'restoration.' Beyond aiding small business recovery post-pandemic, we integrated environmental restoration by developing an app that scans waste, directs users to disposal sites at local businesses, and rewards them with 'ReCoins.' Powered by an image-classification neural network, the app identifies waste and promotes recycling while fostering small business engagement.",
      "rate. Future plans involve implementing reinforcement learning during beta testing to enhance precision through user corrections. A Flask server facilitates communication with the neural network, ensuring seamless waste classification.",
    ],

    embed: [
      {
        src: "https://www.youtube.com/embed/3cQccg12dgQ",
      },
    ],
    imgs: [
      {
        src: "https://i.imgur.com/qZ9qrZb.png",
      },
    ],
    soft_skills: ["Teamwork"],
    tech: ["Flask, Javascript, PyTorch, Expo"],
    more: true,
    project_url: {
      creator: "sabrinabutton",
      repo: "ReCoin",
      url: "https://github.com/sabrinabutton/ReCoin",
    },
  },
  {
    size: 500,
    title: "Markit, Queen's Startup Summit 2nd Place Overall Winner",
    ref: "markit",
    blurb: [
      "In a swift 24-hour span, I collaborated with a team of four to conceive Markit, a startup aimed at curbing food waste. Our innovation streamlines the expiration date tracking process, allowing grocery shoppers to access expiry dates on their purchases via our paired app. By simply tapping their phone on a near-field communication (NFC) chip at checkout, users can retrieve this crucial information. The Markit app then sends timely notifications, preventing food from going to waste in users' fridges. Following our live product pitch, we proudly secured second place overall in the Queen's Startup Summit, standing out among a pool of promising young entrepreneurs.",
    ],
    embed: [
      {
        width: "800",
        height: "450",
        src: "https://www.figma.com/embed?embed_host=share&url=https%3A%2F%2Fwww.figma.com%2Ffile%2FoVKfCGL5Y2QDEBjWh9ndJL%2Fmarkit.io-User-Experience%3Fnode-id%3D0%253A1%26t%3D9ENxn1irzu3J7l1f-1",
      },
    ],
    imgs: [
      { src: "https://i.imgur.com/R0fJzHy.jpg" },

      { src: "https://i.imgur.com/BlUEj7A.png", size: "300px" },
    ],
    soft_skills: ["Teamwork, Agile development, Pitching"],
    tech: ["Near-Field Communications Chips, Figma"],
    more: true,
  },
];

export const work_info = [
  {
    size: 100,
    title: "Ciena | Automation Software Engineer Intern",
    ref: "ciena-2",
    blurb: [
      "- Optimized hardware test software output speeds by increasing code modularity and refactoring algorithms in automated testing scripts using Python on Linux.",
      "- Ran test cases to test the robustness of Ciena’s 6500 equipment.",
      "- Created an internal email notification system notifying of items of urgent attention and test result summaries with Jenkins, Groovy, and HTML.",
    ],

    embed: [],
    imgs: [],
    soft_skills: ["Collecting Requirements, Professional Communications"],
    tech: ["Python, Linux, Hardware Testing, Test Automation"],
    more: false,
  },

  {
    size: 100,
    title: "Ciena | FOS Chamber Development and Integration Intern",
    ref: "ciena-1",
    blurb: [
      "- Assisted in the design and development of the Flower of Sulfur chamber’s, controller box, external display/switch panel, alarms, and sensors.",
      "- Collected requirements from Electrical, Mechanical and Chemical engineers to create controller software, algorithms, and GUI",
      "- Developed software algorithms on the Arduino controller to control the chambers temperature, air speed, humidity, and safety protections.",
      "- Developed a windows based graphical user interface to control the Arduino controller via it’s USB to PC and log sensors data.",
      "- Utilized DVM to debug connectivity and sensor issues.  Soldered connections on external controller.  Made all connections Arduino controller PCB.",
      "- Provided a training session on code and GUI functionality to the team",
      "- Leveraged knowledge of Javascript, React, Node.js, Arduino, C++, Git and analog, digital and PWM",
      "- The project enabled the team to do long term testing without manual intervention.",
    ],
    embed: [],
    imgs: [],
    soft_skills: [
      "Teamwork, Iterative design, Live Project Demonstration, Collecting Requirements",
    ],
    tech: [
      "Arduino, C, React JS, DVMs, analog, digital, and PWM electronic hardware",
    ],
    more: false,
  },

  {
    size: 100,
    title: "Kinaxis | Software Developer Intern",
    ref: "kinaxis",
    blurb: [
      "- Upgraded the Kinaxis recruiting system by integrating an API into the company website to organize job postings and improve the user interface using Javascript, Express.js and REST API POST/GET requests.",
      "- Improved company productivity by developing a chatbot notification system for MS Teams to deliver live project updates, created using Typescript and Node.js, MongoDB for storage, and Azure for hosting.",
      "- Leveraged knowledge of Express, React, Typescript, Azure, Git, Javascript, Node.js, NoSQL databases.",
      "- Provided monthly project demonstrations to the Dev-Ops and Front-end teams, consisting of over 40 people.",
    ],

    embed: [],
    imgs: [],
    soft_skills: ["Live Project Demonstration, Professional Communications"],
    tech: ["React, Javascript, Node JS, APIs, Node.js, Azure, Git"],
    more: false,
  },
];
